In [ ]:
import pandas as pd
import re

In [ ]:
def extractnumber(string):
  return int(re.search(r'\d+(\.\d+)?', string).group())

In [ ]:
items = pd.read_csv('items.csv')

In [ ]:
def rename_value_and_add_sensor_name(items , string):
  df = pd.read_csv(string, index_col='Time')
  df = df.rename(columns={'Value':items[items['ItemId'] == extractnumber(string)]['ItemName'].iloc[0]})
  return df

In [ ]:
items

     ItemId                                 ItemName
0        22  bathroom_shower_coldwater_instantaneous
1        23    kitchen_washingmachine_partial_energy
2        24             kitchen_sink_coldwater_total
3        25               global_waterheater_voltage
4        26        global_waterheater_partial_energy
..      ...                                      ...
232     358                          bedroom_drawer2
233     360              bedroom_switch_middle_right
234     361                       livingroom_window1
235     363                            office_window
236     400                                    label

[237 rows x 2 columns]

In [ ]:
item109 = pd.read_csv('item109.csv')

In [ ]:
item109

                     Time  Value
0     2017-01-30 08:00:17     19
1     2017-01-30 08:05:17     19
2     2017-01-30 08:10:16     19
3     2017-01-30 08:15:16     19
4     2017-01-30 08:20:16     19
...                   ...    ...
2086  2017-02-24 16:19:58     21
2087  2017-02-24 16:24:57     21
2088  2017-02-24 16:29:57     21
2089  2017-02-24 16:34:57     21
2090  2017-02-24 16:39:57     21

[2091 rows x 2 columns]

In [ ]:
import os

directory = '/content/'

# get a list of all the files in the directory
files = os.listdir(directory)
files

['.config',
 'item356.csv',
 'item109.csv',
 'item360.csv',
 'item301.csv',
 'item113.csv',
 'item63.csv',
 'item162.csv',
 'item271.csv',
 'item111.csv',
 'item167.csv',
 'item251.csv',
 'item165.csv',
 'item23.csv',
 'item324.csv',
 'item295.csv',
 'item248.csv',
 'item258.csv',
 'item289.csv',
 'item303.csv',
 'item294.csv',
 'item351.csv',
 'item59.csv',
 'item55.csv',
 'item96.csv',
 'item257.csv',
 'item76.csv',
 'item282.csv',
 'item132.csv',
 'item73.csv',
 'item339.csv',
 'item190.csv',
 'item117.csv',
 'item180.csv',
 'item332.csv',
 'item220.csv',
 'item177.csv',
 'item236.csv',
 'item316.csv',
 'item347.csv',
 'item40.csv',
 'item239.csv',
 'item208.csv',
 'item115.csv',
 'item81.csv',
 'item191.csv',
 'item314.csv',
 'item29.csv',
 'item266.csv',
 'item286.csv',
 'item53.csv',
 'item253.csv',
 'item232.csv',
 'item28.csv',
 'item331.csv',
 'item281.csv',
 'item213.csv',
 'item287.csv',
 'item75.csv',
 'item333.csv',
 'item337.csv',
 'item45.csv',
 'item185.csv',
 'item262.csv',
 'item348.csv',
 'item197.csv',
 'item46.csv',
 'item89.csv',
 'item280.csv',
 'item310.csv',
 'item82.csv',
 'item319.csv',
 'item170.csv',
 'item92.csv',
 'item128.csv',
 'item127.csv',
 'item47.csv',
 'item130.csv',
 'item357.csv',
 'item342.csv',
 'item272.csv',
 'item205.csv',
 'item41.csv',
 'item33.csv',
 'item307.csv',
 'item118.csv',
 'item212.csv',
 'item87.csv',
 'item36.csv',
 'item306.csv',
 'item254.csv',
 'item27.csv',
 'item264.csv',
 'item344.csv',
 'item189.csv',
 'item72.csv',
 'item283.csv',
 'item69.csv',
 'item265.csv',
 'item61.csv',
 'item173.csv',
 'item312.csv',
 'item226.csv',
 'item26.csv',
 'item85.csv',
 'item302.csv',
 'item340.csv',
 'item161.csv',
 'item278.csv',
 'item279.csv',
 'item58.csv',
 'item277.csv',
 'item166.csv',
 'item68.csv',
 'item122.csv',
 'item256.csv',
 'item209.csv',
 'item120.csv',
 'item94.csv',
 'item31.csv',
 'item201.csv',
 'item353.csv',
 'item233.csv',
 'item355.csv',
 'item32.csv',
 'item22.csv',
 'item363.csv',
 'item346.csv',
 'item193.csv',
 'item237.csv',
 'item182.csv',
 'item247.csv',
 'item361.csv',
 'item135.csv',
 'item175.csv',
 'item188.csv',
 'item184.csv',
 'item79.csv',
 'item52.csv',
 'item297.csv',
 'item273.csv',
 'item171.csv',
 'item221.csv',
 'item334.csv',
 'item64.csv',
 'item126.csv',
 'item131.csv',
 'item400.csv',
 'item207.csv',
 'item300.csv',
 'item133.csv',
 'item268.csv',
 'item164.csv',
 'item206.csv',
 'item304.csv',
 'item255.csv',
 'item178.csv',
 'item24.csv',
 'item169.csv',
 'item80.csv',
 'item241.csv',
 'item71.csv',
 'item119.csv',
 'item291.csv',
 'item305.csv',
 'item84.csv',
 'item195.csv',
 'item77.csv',
 'item222.csv',
 'item322.csv',
 'item51.csv',
 'item54.csv',
 'item168.csv',
 'item329.csv',
 'item330.csv',
 'item315.csv',
 'item216.csv',
 'item214.csv',
 'item194.csv',
 'item293.csv',
 'item230.csv',
 'item276.csv',
 'item341.csv',
 'item215.csv',
 'item292.csv',
 'item49.csv',
 'item218.csv',
 'item336.csv',
 'item243.csv',
 'item335.csv',
 'item320.csv',
 'item298.csv',
 'items.csv',
 'item328.csv',
 'item198.csv',
 'item240.csv',
 'item35.csv',
 'item274.csv',
 'item246.csv',
 'item183.csv',
 'item338.csv',
 'item311.csv',
 'item358.csv',
 'item60.csv',
 'item275.csv',
 'item174.csv',
 'item349.csv',
 'item290.csv',
 'item187.csv',
 'item354.csv',
 'item83.csv',
 'item37.csv',
 'item343.csv',
 'item200.csv',
 'item318.csv',
 'item244.csv',
 'item124.csv',
 'item91.csv',
 'item210.csv',
 'item299.csv',
 'item57.csv',
 'item43.csv',
 'item229.csv',
 'item323.csv',
 'item345.csv',
 'item204.csv',
 'item352.csv',
 'item242.csv',
 'item223.csv',
 'item48.csv',
 'item25.csv',
 'item317.csv',
 'item86.csv',
 'item288.csv',
 'item136.csv',
 'item38.csv',
 'item62.csv',
 'item269.csv',
 'item179.csv',
 'sample_data']

In [ ]:
rename_value_and_add_sensor_name(items , "item109.csv")

                     entrance_heater_effective_setpoint
Time
2017-01-30 08:00:17                                  19
2017-01-30 08:05:17                                  19
2017-01-30 08:10:16                                  19
2017-01-30 08:15:16                                  19
2017-01-30 08:20:16                                  19
...                                                 ...
2017-02-24 16:19:58                                  21
2017-02-24 16:24:57                                  21
2017-02-24 16:29:57                                  21
2017-02-24 16:34:57                                  21
2017-02-24 16:39:57                                  21

[2091 rows x 1 columns]

In [ ]:
files.remove('items.csv')
dataframe = pd.DataFrame()
_df = pd.DataFrame()
List = []
for _file in files:
  if re.compile(r'.+\.csv$').match(_file):
    _df = rename_value_and_add_sensor_name(items, _file)
    List.append(_df)

In [ ]:
List

[                    bedroom_switch_middle_left
 Time
 2017-01-30 12:55:36                         ON
 2017-01-30 12:55:37                        OFF
 2017-01-30 13:50:14                         ON
 2017-01-30 13:50:15                        OFF
 2017-01-31 12:51:08                         ON
 ...                                        ...
 2017-02-23 12:51:41                        OFF
 2017-02-23 13:38:11                         ON
 2017-02-23 13:38:12                        OFF
 2017-02-24 12:33:00                         ON
 2017-02-24 12:33:01                        OFF

 [73 rows x 1 columns],                      entrance_heater_effective_setpoint
 Time
 2017-01-30 08:00:17                                  19
 2017-01-30 08:05:17                                  19
 2017-01-30 08:10:16                                  19
 2017-01-30 08:15:16                                  19
 2017-01-30 08:20:16                                  19
 ...                                                 ...
 2017-02-24 16:19:58                                  21
 2017-02-24 16:24:57                                  21
 2017-02-24 16:29:57                                  21
 2017-02-24 16:34:57                                  21
 2017-02-24 16:39:57                                  21

 [2091 rows x 1 columns],                     bedroom_switch_middle_right
 Time
 2017-01-30 13:33:33                          ON
 2017-01-30 13:33:34                         OFF
 2017-01-30 13:51:19                          ON
 2017-01-30 13:51:20                         OFF
 2017-01-31 13:23:23                          ON
 ...                                         ...
 2017-02-23 13:16:04                         OFF
 2017-02-23 13:39:25                          ON
 2017-02-23 13:39:26                         OFF
 2017-02-24 12:34:46                          ON
 2017-02-24 12:34:47                         OFF

 [72 rows x 1 columns],                      kitchen_noise
 Time
 2017-01-30 11:20:44       3.714830
 2017-01-30 11:20:45       1.403500
 2017-01-30 11:47:14       5.936910
 2017-01-30 11:47:15       1.370080
 2017-01-30 11:47:36       3.054410
 ...                            ...
 2017-02-24 12:26:21       4.466290
 2017-02-24 12:26:23       1.646440
 2017-02-24 12:29:40       0.821723
 2017-02-24 12:41:51       2.394720
 2017-02-24 12:41:54       1.054510

 [1653 rows x 1 columns],                      livingroom_couch_plug_consumption
 Time
 2017-01-30 07:58:30                                  0
 2017-01-30 07:58:40                                  0
 2017-01-30 07:58:50                                  0
 2017-01-30 07:59:00                                  0
 2017-01-30 07:59:10                                  0
 ...                                                ...
 2017-02-24 16:40:21                                  0
 2017-02-24 16:40:32                                  0
 2017-02-24 16:40:43                                  0
 2017-02-24 16:40:54                                  0
 2017-02-24 16:41:05                                  0

 [56765 rows x 1 columns],                      global_snow_ext
 Time
 2017-01-30 08:24:19                0
 2017-01-30 09:24:19                0
 2017-01-30 10:24:19                0
 2017-01-30 11:24:19                0
 2017-01-30 12:24:19                0
 ...                              ...
 2017-02-24 11:51:29                0
 2017-02-24 12:51:29                0
 2017-02-24 13:51:29                0
 2017-02-24 14:51:29                0
 2017-02-24 15:51:29                0

 [172 rows x 1 columns],                      bedroom_heater1_effective_setpoint
 Time
 2017-01-30 07:59:55                                  19
 2017-01-30 08:04:55                                  19
 2017-01-30 08:09:55                                  19
 2017-01-30 08:14:55                                  19
 2017-01-30 08:19:54                                  19
 ...                                                 ...
 2017-02-24 16:19:27                                  21
 2017-02-24 16:24:27                                  21
 2017-02-24 16:29:26                                  21
 2017-02-24 16:34:26                                  21
 2017-02-24 16:39:26                                  21

 [2091 rows x 1 columns],                      global_lighting_power
 Time
 2017-01-30 07:58:57                     72
 2017-01-30 08:01:45                     19
 2017-01-30 08:01:57                     45
 2017-01-30 08:02:33                     19
 2017-01-30 08:02:37                     43
 ...                                    ...
 2017-02-24 16:40:06                     73
 2017-02-24 16:40:14                     43
 2017-02-24 16:40:18                     17
 2017-02-24 16:40:26                     72
 2017-02-24 16:41:10                     17

 [2849 rows x 1 columns],                      livingroom_heater2_base_setpoint
 Time
 2017-02-07 11:49:23                                21,                      kitchen_dishwasher_current
 Time
 2017-01-30 08:03:16                           0
 2017-01-30 08:08:09                           0
 2017-01-30 08:13:02                           0
 2017-01-30 08:17:55                           0
 2017-01-30 08:22:48                           0
 ...                                         ...
 2017-02-24 16:17:15                           0
 2017-02-24 16:22:08                           0
 2017-02-24 16:27:01                           0
 2017-02-24 16:31:53                           0
 2017-02-24 16:36:46                           0

 [2140 rows x 1 columns],                      toilet_coldwater_total
 Time
 2017-01-30 14:55:59                     980
 2017-01-30 14:56:11                     981
 2017-01-30 14:56:23                     982
 2017-01-30 14:56:35                     984
 2017-01-31 13:49:25                     986
 2017-01-31 13:49:37                     987
 2017-01-31 13:49:49                     988
 2017-02-01 09:34:58                     990
 2017-02-01 09:35:10                     991
 2017-02-03 12:23:05                     993
 2017-02-03 12:23:17                     994
 2017-02-07 14:56:10                     995
 2017-02-07 14:56:22                     996
 2017-02-07 14:56:34                     998
 2017-02-07 14:56:46                     999
 2017-02-07 14:56:58                    1000
 2017-02-07 14:57:10                    1001
 2017-02-10 12:24:13                    1002
 2017-02-10 12:24:25                    1003
 2017-02-10 12:24:37                    1004
 2017-02-10 12:27:51                    1005
 2017-02-10 12:28:03                    1006
 2017-02-10 12:28:15                    1007
 2017-02-10 12:28:27                    1008
 2017-02-10 12:28:40                    1010
 2017-02-10 12:28:52                    1011
 2017-02-10 15:44:10                    1013
 2017-02-10 15:44:22                    1014
 2017-02-10 15:44:35                    1015
 2017-02-10 15:44:47                    1016
 2017-02-10 15:44:59                    1017
 2017-02-16 15:42:01                    1019
 2017-02-16 15:42:13                    1020
 2017-02-16 15:42:25                    1021
 2017-02-16 15:42:37                    1023
 2017-02-16 15:42:49                    1024
 2017-02-16 15:43:01                    1026
 2017-02-17 12:24:54                    1027
 2017-02-17 12:25:06                    1029
 2017-02-17 12:25:18                    1030
 2017-02-17 12:25:30                    1031
 2017-02-17 12:25:42                    1032
 2017-02-17 12:25:54                    1034
 2017-02-17 12:26:06                    1035
 2017-02-21 14:12:37                    1037
 2017-02-21 14:12:49                    1038
 2017-02-21 14:13:02                    1040
 2017-02-21 14:13:14                    1041
 2017-02-21 14:13:26                    1042
 2017-02-21 14:13:38                    1044
 2017-02-21 14:13:50                    1045
 2017-02-21 14:14:02                    1046
 2017-02-24 12:31:34                    1047
 2017-02-24 12:31:46                    1048
 2017-02-24 12:31:58                    1049
 2017-02-24 12:32:10                    1051
 2017-02-24 12:32:22                    1052,                      kitchen_hood_voltage
 Time
 2017-01-30 07:59:37                238.13
 2017-01-30 08:04:30                238.93
 2017-01-30 08:09:23                238.16
 2017-01-30 08:14:16                238.11
 2017-01-30 08:19:09                238.01
 ...                                   ...
 2017-02-24 16:17:36                238.35
 2017-02-24 16:22:29                238.03
 2017-02-24 16:27:22                237.38
 2017-02-24 16:32:15                237.55
 2017-02-24 16:37:08                238.24

 [2144 rows x 1 columns],                      kitchen_washingmachine_partial_energy
 Time
 2017-01-30 08:03:14                                   3942
 2017-01-30 08:08:05                                   3942
 2017-01-30 08:13:01                                   3942
 2017-01-30 08:17:52                                   3942
 2017-01-30 08:22:44                                   3942
 ...                                                    ...
 2017-02-24 16:17:12                                   3942
 2017-02-24 16:22:03                                   3942
 2017-02-24 16:26:59                                   3942
 2017-02-24 16:31:51                                   3942
 2017-02-24 16:36:47                                   3942

 [2140 rows x 1 columns],                     walkway_switch2_bottom_left
 Time
 2017-01-30 08:02:26                          ON
 2017-01-30 08:02:27                         OFF
 2017-01-30 08:02:28                         OFF
 2017-02-06 08:24:21                          ON
 2017-02-06 08:24:22                         OFF
 2017-02-13 08:27:56                          ON
 2017-02-13 08:27:57                         OFF
 2017-02-24 08:31:50                          ON
 2017-02-24 08:31:51                         OFF,                      livingroom_shutter5
 Time
 2017-01-30 07:59:28                    0
 2017-01-30 07:59:50                    0
 2017-01-30 16:58:57                  100
 2017-01-30 16:59:19                  100
 2017-01-31 08:28:59                    0
 ...                                  ...
 2017-02-23 16:56:13                  100
 2017-02-24 08:12:18                    0
 2017-02-24 08:12:39                    0
 2017-02-24 16:40:25                  100
 2017-02-24 16:40:47                  100

 [83 rows x 1 columns],                      kitchen_hood_total_energy
 Time
 2017-01-30 08:02:14                        432
 2017-01-30 08:07:05                        432
 2017-01-30 08:12:01                        432
 2017-01-30 08:16:52                        432
 2017-01-30 08:21:44                        432
 ...                                        ...
 2017-02-24 16:21:05                        763
 2017-02-24 16:26:01                        763
 2017-02-24 16:30:52                        763
 2017-02-24 16:35:43                        763
 2017-02-24 16:40:40                        763

 [2143 rows x 1 columns],                      bathroom_heater_command
 Time
 2017-01-30 08:00:33                        0
 2017-01-30 08:05:33                        0
 2017-01-30 08:10:32                        0
 2017-01-30 08:15:32                        0
 2017-01-30 08:20:32                        0
 ...                                      ...
 2017-02-24 16:20:25                        0
 2017-02-24 16:25:24                        0
 2017-02-24 16:30:24                        0
 2017-02-24 16:35:24                        0
 2017-02-24 16:40:24                        0

 [2253 rows x 1 columns],                      walkway_noise
 Time
 2017-01-30 07:58:56       0.965772
 2017-01-30 07:58:57       0.322290
 2017-01-30 07:59:00       0.140185
 2017-01-30 07:59:23       0.315044
 2017-01-30 07:59:27       0.137207
 ...                            ...
 2017-02-24 16:40:53       0.395243
 2017-02-24 16:41:01       0.133975
 2017-02-24 16:41:07       0.313907
 2017-02-24 16:41:08       0.156910
 2017-02-24 16:41:16       0.675130

 [4700 rows x 1 columns],                      entrance_noise
 Time
 2017-01-30 07:58:56         5.84291
 2017-01-30 07:58:57         2.72151
 2017-01-31 08:28:55         5.93105
 2017-01-31 08:28:56         1.53157
 2017-01-31 12:08:08         5.81408
 ...                             ...
 2017-02-23 11:58:41         1.48662
 2017-02-23 16:56:37         4.19023
 2017-02-24 12:00:38         2.99145
 2017-02-24 12:07:03         1.47572
 2017-02-24 16:41:15         5.07239

 [98 rows x 1 columns],                      livingroom_shutter4
 Time
 2017-01-30 07:59:28                    0
 2017-01-30 07:59:50                    0
 2017-01-30 16:58:57                  100
 2017-01-30 16:59:19                  100
 2017-01-31 08:28:59                    0
 ...                                  ...
 2017-02-23 16:56:13                  100
 2017-02-24 08:12:18                    0
 2017-02-24 08:12:40                    0
 2017-02-24 16:40:25                  100
 2017-02-24 16:40:47                  100

 [83 rows x 1 columns],                     livingroom_switch2_top_left
 Time
 2017-01-30 07:59:27                          ON
 2017-01-30 07:59:28                         OFF
 2017-01-31 08:28:58                          ON
 2017-01-31 08:28:59                         OFF
 2017-02-01 08:07:32                          ON
 2017-02-01 08:07:33                         OFF
 2017-02-02 08:03:08                          ON
 2017-02-02 08:03:09                         OFF
 2017-02-02 16:56:32                          ON
 2017-02-02 16:56:33                         OFF
 2017-02-03 07:58:52                          ON
 2017-02-03 07:58:53                         OFF
 2017-02-06 08:24:52                          ON
 2017-02-06 08:24:53                         OFF
 2017-02-07 08:00:41                          ON
 2017-02-07 08:00:42                         OFF
 2017-02-08 08:03:56                          ON
 2017-02-08 08:03:57                         OFF
 2017-02-09 08:02:09                          ON
 2017-02-09 08:02:10                         OFF
 2017-02-10 08:10:28                          ON
 2017-02-10 08:10:29                         OFF
 2017-02-13 08:07:27                          ON
 2017-02-13 08:07:28                         OFF
 2017-02-14 08:31:39                          ON
 2017-02-14 08:31:40                         OFF
 2017-02-15 08:18:02                          ON
 2017-02-15 08:18:03                         OFF
 2017-02-16 08:02:31                          ON
 2017-02-16 08:02:32                         OFF
 2017-02-17 08:00:15                          ON
 2017-02-17 08:00:16                         OFF
 2017-02-20 08:54:39                          ON
 2017-02-20 08:54:40                         OFF
 2017-02-21 08:04:50                          ON
 2017-02-21 08:04:51                         OFF
 2017-02-22 08:07:45                          ON
 2017-02-22 08:07:46                         OFF
 2017-02-23 08:08:09                          ON
 2017-02-23 08:08:10                         OFF
 2017-02-24 08:12:17                          ON
 2017-02-24 08:12:18                         OFF,                      global_rain_ext
 Time
 2017-01-30 08:24:19              0.0
 2017-01-30 09:24:19              0.0
 2017-01-30 10:24:19              0.0
 2017-01-30 11:24:19              0.0
 2017-01-30 12:24:19              0.0
 ...                              ...
 2017-02-24 11:51:29              0.0
 2017-02-24 12:51:29              0.0
 2017-02-24 13:51:29              0.0
 2017-02-24 14:51:29              0.0
 2017-02-24 15:51:29              0.0

 [172 rows x 1 columns],                      global_wind_speed_ext
 Time
 2017-01-30 08:24:19                   2.60
 2017-01-30 09:24:19                   2.10
 2017-01-30 10:24:19                   1.00
 2017-01-30 11:24:19                   1.00
 2017-01-30 12:24:19                   0.76
 ...                                    ...
 2017-02-24 11:51:29                   6.70
 2017-02-24 12:51:29                   5.10
 2017-02-24 13:51:29                   7.20
 2017-02-24 14:51:29                   6.70
 2017-02-24 15:51:29                   6.70

 [172 rows x 1 columns],                      global_waterheater_total_energy
 Time
 2017-01-30 07:58:44                           179071
 2017-01-30 08:03:35                           179071
 2017-01-30 08:08:26                           179078
 2017-01-30 08:13:23                           179087
 2017-01-30 08:18:14                           179088
 ...                                              ...
 2017-02-24 16:23:10                           189222
 2017-02-24 16:27:19                           189232
 2017-02-24 16:28:01                           189232
 2017-02-24 16:32:57                           189240
 2017-02-24 16:37:48                           189241

 [2220 rows x 1 columns],                      global_lighting_current
 Time
 2017-01-30 07:59:42                     0.38
 2017-01-30 08:04:35                     0.36
 2017-01-30 08:09:28                     0.36
 2017-01-30 08:14:21                     0.35
 2017-01-30 08:19:14                     0.35
 ...                                      ...
 2017-02-24 16:19:17                     0.29
 2017-02-24 16:24:10                     0.29
 2017-02-24 16:29:03                     0.29
 2017-02-24 16:33:56                     0.29
 2017-02-24 16:38:49                     0.29

 [2140 rows x 1 columns],                      livingroom_heater2_temperature
 Time
 2017-01-30 08:00:04                            19.9
 2017-01-30 08:05:04                            19.9
 2017-01-30 08:08:37                            19.7
 2017-01-30 08:10:04                            19.7
 2017-01-30 08:15:03                            19.7
 ...                                             ...
 2017-02-24 16:24:38                            21.9
 2017-02-24 16:29:38                            21.9
 2017-02-24 16:34:38                            21.9
 2017-02-24 16:35:01                            21.7
 2017-02-24 16:39:37                            21.7

 [2846 rows x 1 columns],                     livingroom_tv_status
 Time
 2017-01-30 07:59:02                  OFF
 2017-01-30 08:00:02                  OFF
 2017-01-30 08:01:02                  OFF
 2017-01-30 08:02:02                  OFF
 2017-01-30 08:03:02                  OFF
 ...                                  ...
 2017-02-24 16:37:03                  OFF
 2017-02-24 16:38:03                  OFF
 2017-02-24 16:39:03                  OFF
 2017-02-24 16:40:03                  OFF
 2017-02-24 16:41:03                  OFF

 [10455 rows x 1 columns],                      office_tv_plug_consumption
 Time
 2017-01-30 07:58:30                           0
 2017-01-30 07:58:40                           0
 2017-01-30 07:58:50                           0
 2017-01-30 07:59:00                           0
 2017-01-30 07:59:10                           0
 ...                                         ...
 2017-02-24 16:40:32                           0
 2017-02-24 16:40:43                           0
 2017-02-24 16:40:54                           0
 2017-02-24 16:41:05                           0
 2017-02-24 16:41:16                           0

 [56891 rows x 1 columns],                      kitchen_fridge_power
 Time
 2017-01-30 08:01:19                     0
 2017-01-30 08:06:12                     0
 2017-01-30 08:11:05                     0
 2017-01-30 08:15:58                     0
 2017-01-30 08:20:51                     0
 ...                                   ...
 2017-02-24 16:21:55                    67
 2017-02-24 16:25:15                    62
 2017-02-24 16:30:08                    58
 2017-02-24 16:34:43                     0
 2017-02-24 16:39:36                     0


In [ ]:
all_data = pd.concat(List, axis=1)
all_data = all_data.sort_values(by='Time')

In [ ]:
all_data.shape

(383714, 237)

In [ ]:
display(all_data)

,bedroom_switch_middle_left,entrance_heater_effective_setpoint,bedroom_switch_middle_right,kitchen_noise,livingroom_couch_plug_consumption,global_snow_ext,bedroom_heater1_effective_setpoint,global_lighting_power,livingroom_heater2_base_setpoint,kitchen_dishwasher_current,...,kitchen_hood_partial_energy,global_waterheater_voltage,kitchen_cupboard4,bathroom_sink_coldwater_instantaneous,bedroom_noise,kitchen_humidity,kitchen_oven_power,global_commonID_ext,kitchen_presence,livingroom_luminosity
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-30 07:58:30,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-24 16:41:11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-24 16:41:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-24 16:41:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-24 16:41:15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-24 16:41:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
all_data.head()

,bedroom_switch_middle_left,entrance_heater_effective_setpoint,bedroom_switch_middle_right,kitchen_noise,livingroom_couch_plug_consumption,global_snow_ext,bedroom_heater1_effective_setpoint,global_lighting_power,livingroom_heater2_base_setpoint,kitchen_dishwasher_current,...,kitchen_hood_partial_energy,global_waterheater_voltage,kitchen_cupboard4,bathroom_sink_coldwater_instantaneous,bedroom_noise,kitchen_humidity,kitchen_oven_power,global_commonID_ext,kitchen_presence,livingroom_luminosity
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-30 07:58:30,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# fill missing values with the last valid observation from the past
all_data = all_data.fillna(method='ffill')

all_data.head()

,bedroom_switch_middle_left,entrance_heater_effective_setpoint,bedroom_switch_middle_right,kitchen_noise,livingroom_couch_plug_consumption,global_snow_ext,bedroom_heater1_effective_setpoint,global_lighting_power,livingroom_heater2_base_setpoint,kitchen_dishwasher_current,...,kitchen_hood_partial_energy,global_waterheater_voltage,kitchen_cupboard4,bathroom_sink_coldwater_instantaneous,bedroom_noise,kitchen_humidity,kitchen_oven_power,global_commonID_ext,kitchen_presence,livingroom_luminosity
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-30 07:58:30,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:32,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:33,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:36,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30 07:58:38,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import numpy as np

# select columns with numeric data types
numerical_cols = all_data.select_dtypes(include=np.number).columns.tolist()

# print the list of numerical columns
print(numerical_cols)

['entrance_heater_effective_setpoint', 'kitchen_noise', 'livingroom_couch_plug_consumption', 'global_snow_ext', 'bedroom_heater1_effective_setpoint', 'global_lighting_power', 'livingroom_heater2_base_setpoint', 'kitchen_dishwasher_current', 'toilet_coldwater_total', 'kitchen_hood_voltage', 'kitchen_washingmachine_partial_energy', 'livingroom_shutter5', 'kitchen_hood_total_energy', 'bathroom_heater_command', 'walkway_noise', 'entrance_noise', 'livingroom_shutter4', 'global_rain_ext', 'global_wind_speed_ext', 'global_waterheater_total_energy', 'global_lighting_current', 'livingroom_heater2_temperature', 'office_tv_plug_consumption', 'kitchen_fridge_power', 'bathroom_luminosity', 'livingroom_tv_plug_consumption', 'office_AC_setpoint', 'bedroom_light4', 'office_heater_effective_mode', 'global_lighting_total_energy', 'entrance_heater_base_setpoint', 'office_heater_command', 'bedroom_light2', 'livingroom_table_luminosity', 'global_voltage', 'bedroom_temperature', 'bathroom_sink_coldwater_total', 'global_lighting_partial_energy', 'livingroom_couch_noise', 'global_temperature_feel_ext', 'livingroom_humidity', 'kitchen_oven_current', 'livingroom_heater1_command', 'staircase_light', 'office_noise', 'kitchen_sink_hotwater_total', 'livingroom_heater2_effective_setpoint', 'bedroom_humidity', 'livingroom_heater1_effective_mode', 'bedroom_heater2_effective_setpoint', 'livingroom_heater2_command', 'bedroom_shutter1', 'global_active_power', 'kitchen_hood_current', 'entrance_heater_temperature', 'bedroom_CO2', 'livingroom_table_plug_consumption', 'bathroom_CO2', 'bathroom_temperature', 'global_heaters_temperature', 'global_waterheater_current', 'kitchen_dishwasher_voltage', 'global_shutters_voltage', 'livingroom_heater1_effective_setpoint', 'livingroom_light1', 'bathroom_heater_temperature', 'kitchen_cooktop_current', 'toilet_coldwater_instantaneous', 'kitchen_oven_voltage', 'bathroom_sink_hotwater_instantaneous', 'kitchen_sink_coldwater_instantaneous', 'livingroom_heater2_effective_mode', 'global_shutters_current', 'kitchen_fridge_current', 'kitchen_washingmachine_total_energy', 'bedroom_shutter2', 'bathroom_light2', 'global_waterheater_partial_energy', 'global_frequency', 'kitchen_luminosity', 'bedroom_heater2_command', 'entrance_heater_command', 'global_pressure_ext', 'kitchen_oven_partial_energy', 'global_shutters_power', 'office_luminosity', 'kitchen_cooktop_total_energy', 'kitchen_washingmachine_voltage', 'bathroom_light1', 'bedroom_luminosity', 'bathroom_heater_effective_setpoint', 'bathroom_shower_hotwater_instantaneous', 'bathroom_humidity', 'bathroom_shower_coldwater_total', 'bathroom_shower_coldwater_instantaneous', 'kitchen_dishwasher_partial_energy', 'kitchen_fridge_voltage', 'office_heater_effective_setpoint', 'office_heater_temperature', 'bathroom_sink_hotwater_total', 'kitchen_cooktop_voltage', 'kitchen_hood_power', 'kitchen_sink_hotwater_instantaneous', 'global_current', 'global_condition_id_ext', 'office_AC_mode', 'bedroom_heater2_effective_mode', 'walkway_light', 'global_clouds_ext', 'global_shutters_total_energy', 'bedroom_heater1_effective_mode', 'bedroom_light1', 'livingroom_temperature', 'livingroom_CO2', 'global_shutters_partial_energy', 'bathroom_shower_hotwater_total', 'kitchen_cooktop_partial_energy', 'global_waterheater_power', 'kitchen_sink_coldwater_total', 'kitchen_oven_total_energy', 'global_power_factor', 'kitchen_washingmachine_current', 'global_coldwater_instantaneous', 'office_desk_plug_consumption', 'global_active_energy', 'global_coldwater_total', 'bathroom_heater_effective_mode', 'office_light', 'global_humidity_ext', 'livingroom_AC_setpoint', 'office_heater_base_setpoint', 'bedroom_light3', 'kitchen_dishwasher_total_energy', 'livingroom_shutter3', 'kitchen_light2', 'kitchen_cooktop_power', 'toilet_light', 'livingroom_shutter2', 'livingroom_light2', 'livingroom_heater1_temperature', 'kitchen_dishwasher_power', 'global_heaters_setpoint', 'bedroom_AC_setpoint', 'kitchen_temperature', 'bedroom_heater2_temperature', 'kitchen_fridge_partial_energy', 'office_shutter', 'global_temperature_ext', 'bedroom_heater1_command', 'bathroom_heater_base_setpoint', 'bedroom_bed_pressure', 'livingroom_table_noise', 'global_lighting_voltage', 'global_gas_total', 'kitchen_washingmachine_power', 'bedroom_heater2_base_setpoint', 'entrance_heater_effective_mode', 'bedroom_heater1_temperature', 'entrance_light1', 'livingroom_shutter1', 'livingroom_heater1_base_setpoint', 'kitchen_CO2', 'kitchen_fridge_total_energy', 'bedroom_heater1_base_setpoint', 'kitchen_light1', 'kitchen_hood_partial_energy', 'global_waterheater_voltage', 'bathroom_sink_coldwater_instantaneous', 'bedroom_noise', 'kitchen_humidity', 'kitchen_oven_power', 'livingroom_luminosity']

In [ ]:
# select columns with object data type
categorical_cols = all_data.select_dtypes(include=['object']).columns.tolist()

# print the list of categorical columns
print(categorical_cols)

['bedroom_switch_middle_left', 'bedroom_switch_middle_right', 'walkway_switch2_bottom_left', 'livingroom_switch2_top_left', 'livingroom_tv_status', 'bedroom_closet_door', 'bathroom_switch_bottom_right', 'kitchen_cupboard3', 'toilet_switch_left', 'kitchen_fridge_door', 'livingroom_presence_table', 'bathroom_switch_bottom_left', 'bathroom_switch_top_right', 'bedroom_switch_bottom_left', 'livingroom_presence_couch', 'bedroom_presence', 'toilet_switch_right', 'walkway_switch1_bottom_left', 'bedroom_drawer1', 'office_switch_right', 'walkway_switch1_bottom_right', 'entrance_switch_left', 'staircase_switch_right', 'office_tv_status', 'global_wind_direction_ext', 'kitchen_switch_bottom_right', 'bedroom_door', 'office_presence', 'livingroom_switch1_top_left', 'kitchen_cupboard5', 'office_window', 'kitchen_switch_bottom_left', 'livingroom_window1', 'livingroom_switch1_top_right', 'bathroom_door', 'label', 'kitchen_cupboard1', 'kitchen_switch_top_right', 'livingroom_switch1_bottom_left', 'entrance_door', 'walkway_switch1_top_right', 'global_pressure_trend_ext', 'walkway_switch2_top_right', 'bathroom_switch_top_left', 'kitchen_cupboard2', 'office_switch_left', 'bathroom_presence', 'bedroom_switch_top_right', 'bedroom_switch_top_left', 'walkway_switch1_top_left', 'livingroom_switch2_top_right', 'walkway_switch2_bottom_right', 'bedroom_switch_bottom_right', 'bedroom_drawer2', 'office_switch_middle', 'global_waterheater_status', 'office_door', 'staircase_switch_left', 'global_condition_ext', 'walkway_switch2_top_left', 'kitchen_switch_top_left', 'bathroom_shower_door', 'kitchen_cupboard4', 'global_commonID_ext', 'kitchen_presence']

In [ ]:
# replace remaining missing values with zero for numerical sensors and with the first valid observation for categorical sensors
# replace with the actual categorical column names

for col in numerical_cols:
    all_data[col] = all_data[col].fillna(0)

for col in categorical_cols:
    all_data[col] = all_data[col].fillna(method='bfill')

In [ ]:
all_data

,bedroom_switch_middle_left,entrance_heater_effective_setpoint,bedroom_switch_middle_right,kitchen_noise,livingroom_couch_plug_consumption,global_snow_ext,bedroom_heater1_effective_setpoint,global_lighting_power,livingroom_heater2_base_setpoint,kitchen_dishwasher_current,...,kitchen_hood_partial_energy,global_waterheater_voltage,kitchen_cupboard4,bathroom_sink_coldwater_instantaneous,bedroom_noise,kitchen_humidity,kitchen_oven_power,global_commonID_ext,kitchen_presence,livingroom_luminosity
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-30 07:58:30,ON,0.0,ON,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,OPEN,0.0,0.000000,0.0,0.0,partly-cloudy-day,ON,0.0
2017-01-30 07:58:32,ON,0.0,ON,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,OPEN,0.0,0.000000,0.0,0.0,partly-cloudy-day,ON,0.0
2017-01-30 07:58:33,ON,0.0,ON,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,OPEN,0.0,0.000000,0.0,0.0,partly-cloudy-day,ON,0.0
2017-01-30 07:58:36,ON,0.0,ON,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,OPEN,0.0,0.000000,0.0,0.0,partly-cloudy-day,ON,0.0
2017-01-30 07:58:38,ON,0.0,ON,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,OPEN,0.0,0.000000,0.0,0.0,partly-cloudy-day,ON,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-24 16:41:11,OFF,21.0,OFF,1.05451,0.0,0.0,21.0,17.0,21.0,0.0,...,763.0,238.67,CLOSED,0.0,0.517463,35.0,0.0,cloudy,OFF,11.0
2017-02-24 16:41:13,OFF,21.0,OFF,1.05451,0.0,0.0,21.0,17.0,21.0,0.0,...,763.0,238.67,CLOSED,0.0,0.517463,35.0,0.0,cloudy,OFF,11.0
2017-02-24 16:41:14,OFF,21.0,OFF,1.05451,0.0,0.0,21.0,17.0,21.0,0.0,...,763.0,238.67,CLOSED,0.0,0.517463,35.0,0.0,cloudy,OFF,11.0
2017-02-24 16:41:15,OFF,21.0,OFF,1.05451,0.0,0.0,21.0,17.0,21.0,0.0,...,763.0,238.67,CLOSED,0.0,0.517463,35.0,0.0,cloudy,OFF,11.0
2017-02-24 16:41:16,OFF,21.0,OFF,1.05451,0.0,0.0,21.0,17.0,21.0,0.0,...,763.0,238.67,CLOSED,0.0,0.517463,35.0,0.0,cloudy,OFF,11.0

In [ ]:
# check for missing values in each column
missing_values = all_data.isnull().sum()

# print the number of missing values in each column
print(missing_values)

bedroom_switch_middle_left            0
entrance_heater_effective_setpoint    0
bedroom_switch_middle_right           0
kitchen_noise                         0
livingroom_couch_plug_consumption     0
                                     ..
kitchen_humidity                      0
kitchen_oven_power                    0
global_commonID_ext                   0
kitchen_presence                      0
livingroom_luminosity                 0
Length: 237, dtype: int64

In [ ]:
# Reorder a Label column and put it in the last position
column_to_move = "label"
new_order = list(all_data.columns.drop(column_to_move)) + [column_to_move]
all_data = all_data[new_order]

In [ ]:
# write the DataFrame to a CSV file (Filling missing values)
all_data.to_csv('sensor_data_processed_filling_missing_values.csv', index=False)

# Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler, LabelBinarizer, OneHotEncoder, MultiLabelBinarizer

In [ ]:
# Get the list of binary column names
binary_cols = []
for col in all_data.columns:
    if all_data[col].nunique() == 2:  # Check if the column has only two unique values
        binary_cols.append(col)

binary_cols

['bedroom_switch_middle_left',
 'bedroom_switch_middle_right',
 'livingroom_heater2_base_setpoint',
 'kitchen_washingmachine_partial_energy',
 'walkway_switch2_bottom_left',
 'livingroom_shutter5',
 'livingroom_shutter4',
 'livingroom_switch2_top_left',
 'livingroom_tv_status',
 'bedroom_closet_door',
 'bathroom_switch_bottom_right',
 'bedroom_light4',
 'office_heater_effective_mode',
 'kitchen_cupboard3',
 'toilet_switch_left',
 'entrance_heater_base_setpoint',
 'bedroom_light2',
 'kitchen_fridge_door',
 'livingroom_presence_table',
 'bathroom_switch_bottom_left',
 'staircase_light',
 'bathroom_switch_top_right',
 'bedroom_switch_bottom_left',
 'livingroom_presence_couch',
 'bedroom_presence',
 'toilet_switch_right',
 'livingroom_heater1_effective_mode',
 'bedroom_shutter1',
 'walkway_switch1_bottom_left',
 'bedroom_drawer1',
 'office_switch_right',
 'walkway_switch1_bottom_right',
 'livingroom_light1',
 'entrance_switch_left',
 'bathroom_sink_hotwater_instantaneous',
 'staircase_switch_right',
 'livingroom_heater2_effective_mode',
 'office_tv_status',
 'kitchen_washingmachine_total_energy',
 'bedroom_shutter2',
 'bathroom_light2',
 'kitchen_switch_bottom_right',
 'bedroom_door',
 'bathroom_light1',
 'office_presence',
 'livingroom_switch1_top_left',
 'kitchen_cupboard5',
 'office_window',
 'kitchen_switch_bottom_left',
 'kitchen_dishwasher_partial_energy',
 'livingroom_window1',
 'livingroom_switch1_top_right',
 'bedroom_heater2_effective_mode',
 'walkway_light',
 'bathroom_door',
 'bedroom_heater1_effective_mode',
 'bedroom_light1',
 'kitchen_cupboard1',
 'kitchen_switch_top_right',
 'livingroom_switch1_bottom_left',
 'entrance_door',
 'bathroom_heater_effective_mode',
 'office_light',
 'walkway_switch1_top_right',
 'livingroom_AC_setpoint',
 'walkway_switch2_top_right',
 'bathroom_switch_top_left',
 'kitchen_cupboard2',
 'office_heater_base_setpoint',
 'bedroom_light3',
 'kitchen_dishwasher_total_energy',
 'livingroom_shutter3',
 'kitchen_light2',
 'office_switch_left',
 'toilet_light',
 'livingroom_shutter2',
 'bathroom_presence',
 'livingroom_light2',
 'bedroom_switch_top_right',
 'bedroom_switch_top_left',
 'walkway_switch1_top_left',
 'livingroom_switch2_top_right',
 'walkway_switch2_bottom_right',
 'global_heaters_setpoint',
 'bedroom_AC_setpoint',
 'bedroom_switch_bottom_right',
 'office_shutter',
 'bedroom_drawer2',
 'bathroom_heater_base_setpoint',
 'office_switch_middle',
 'global_waterheater_status',
 'office_door',
 'staircase_switch_left',
 'bedroom_heater2_base_setpoint',
 'entrance_heater_effective_mode',
 'entrance_light1',
 'livingroom_shutter1',
 'livingroom_heater1_base_setpoint',
 'walkway_switch2_top_left',
 'kitchen_switch_top_left',
 'bathroom_shower_door',
 'bedroom_heater1_base_setpoint',
 'kitchen_light1',
 'kitchen_cupboard4',
 'kitchen_presence']

In [ ]:
# Get the list of columns with multiple categories
multi_cols = []
for col in all_data.columns:
    if all_data[col].dtype == "object" and all_data[col].nunique() > 2:  # Check if the column is categorical and has more than two unique values
        multi_cols.append(col)
  
multi_cols

['global_wind_direction_ext',
 'global_pressure_trend_ext',
 'global_condition_ext',
 'global_commonID_ext',
 'label']

In [ ]:
# select columns with numeric data types
numerical_cols = all_data.select_dtypes(include=np.number).columns.tolist()

# print the list of numerical columns
print(numerical_cols)

['entrance_heater_effective_setpoint', 'kitchen_noise', 'livingroom_couch_plug_consumption', 'global_snow_ext', 'bedroom_heater1_effective_setpoint', 'global_lighting_power', 'livingroom_heater2_base_setpoint', 'kitchen_dishwasher_current', 'toilet_coldwater_total', 'kitchen_hood_voltage', 'kitchen_washingmachine_partial_energy', 'livingroom_shutter5', 'kitchen_hood_total_energy', 'bathroom_heater_command', 'walkway_noise', 'entrance_noise', 'livingroom_shutter4', 'global_rain_ext', 'global_wind_speed_ext', 'global_waterheater_total_energy', 'global_lighting_current', 'livingroom_heater2_temperature', 'office_tv_plug_consumption', 'kitchen_fridge_power', 'bathroom_luminosity', 'livingroom_tv_plug_consumption', 'office_AC_setpoint', 'bedroom_light4', 'office_heater_effective_mode', 'global_lighting_total_energy', 'entrance_heater_base_setpoint', 'office_heater_command', 'bedroom_light2', 'livingroom_table_luminosity', 'global_voltage', 'bedroom_temperature', 'bathroom_sink_coldwater_total', 'global_lighting_partial_energy', 'livingroom_couch_noise', 'global_temperature_feel_ext', 'livingroom_humidity', 'kitchen_oven_current', 'livingroom_heater1_command', 'staircase_light', 'office_noise', 'kitchen_sink_hotwater_total', 'livingroom_heater2_effective_setpoint', 'bedroom_humidity', 'livingroom_heater1_effective_mode', 'bedroom_heater2_effective_setpoint', 'livingroom_heater2_command', 'bedroom_shutter1', 'global_active_power', 'kitchen_hood_current', 'entrance_heater_temperature', 'bedroom_CO2', 'livingroom_table_plug_consumption', 'bathroom_CO2', 'bathroom_temperature', 'global_heaters_temperature', 'global_waterheater_current', 'kitchen_dishwasher_voltage', 'global_shutters_voltage', 'livingroom_heater1_effective_setpoint', 'livingroom_light1', 'bathroom_heater_temperature', 'kitchen_cooktop_current', 'toilet_coldwater_instantaneous', 'kitchen_oven_voltage', 'bathroom_sink_hotwater_instantaneous', 'kitchen_sink_coldwater_instantaneous', 'livingroom_heater2_effective_mode', 'global_shutters_current', 'kitchen_fridge_current', 'kitchen_washingmachine_total_energy', 'bedroom_shutter2', 'bathroom_light2', 'global_waterheater_partial_energy', 'global_frequency', 'kitchen_luminosity', 'bedroom_heater2_command', 'entrance_heater_command', 'global_pressure_ext', 'kitchen_oven_partial_energy', 'global_shutters_power', 'office_luminosity', 'kitchen_cooktop_total_energy', 'kitchen_washingmachine_voltage', 'bathroom_light1', 'bedroom_luminosity', 'bathroom_heater_effective_setpoint', 'bathroom_shower_hotwater_instantaneous', 'bathroom_humidity', 'bathroom_shower_coldwater_total', 'bathroom_shower_coldwater_instantaneous', 'kitchen_dishwasher_partial_energy', 'kitchen_fridge_voltage', 'office_heater_effective_setpoint', 'office_heater_temperature', 'bathroom_sink_hotwater_total', 'kitchen_cooktop_voltage', 'kitchen_hood_power', 'kitchen_sink_hotwater_instantaneous', 'global_current', 'global_condition_id_ext', 'office_AC_mode', 'bedroom_heater2_effective_mode', 'walkway_light', 'global_clouds_ext', 'global_shutters_total_energy', 'bedroom_heater1_effective_mode', 'bedroom_light1', 'livingroom_temperature', 'livingroom_CO2', 'global_shutters_partial_energy', 'bathroom_shower_hotwater_total', 'kitchen_cooktop_partial_energy', 'global_waterheater_power', 'kitchen_sink_coldwater_total', 'kitchen_oven_total_energy', 'global_power_factor', 'kitchen_washingmachine_current', 'global_coldwater_instantaneous', 'office_desk_plug_consumption', 'global_active_energy', 'global_coldwater_total', 'bathroom_heater_effective_mode', 'office_light', 'global_humidity_ext', 'livingroom_AC_setpoint', 'office_heater_base_setpoint', 'bedroom_light3', 'kitchen_dishwasher_total_energy', 'livingroom_shutter3', 'kitchen_light2', 'kitchen_cooktop_power', 'toilet_light', 'livingroom_shutter2', 'livingroom_light2', 'livingroom_heater1_temperature', 'kitchen_dishwasher_power', 'global_heaters_setpoint', 'bedroom_AC_setpoint', 'kitchen_temperature', 'bedroom_heater2_temperature', 'kitchen_fridge_partial_energy', 'office_shutter', 'global_temperature_ext', 'bedroom_heater1_command', 'bathroom_heater_base_setpoint', 'bedroom_bed_pressure', 'livingroom_table_noise', 'global_lighting_voltage', 'global_gas_total', 'kitchen_washingmachine_power', 'bedroom_heater2_base_setpoint', 'entrance_heater_effective_mode', 'bedroom_heater1_temperature', 'entrance_light1', 'livingroom_shutter1', 'livingroom_heater1_base_setpoint', 'kitchen_CO2', 'kitchen_fridge_total_energy', 'bedroom_heater1_base_setpoint', 'kitchen_light1', 'kitchen_hood_partial_energy', 'global_waterheater_voltage', 'bathroom_sink_coldwater_instantaneous', 'bedroom_noise', 'kitchen_humidity', 'kitchen_oven_power', 'livingroom_luminosity']

In [ ]:
all_data['label']

Time
2017-01-30 07:58:30    START:Entrance|Entering
2017-01-30 07:58:32    START:Entrance|Entering
2017-01-30 07:58:33    START:Entrance|Entering
2017-01-30 07:58:36    START:Entrance|Entering
2017-01-30 07:58:38    START:Entrance|Entering
                                ...
2017-02-24 16:41:11     START:Entrance|Leaving
2017-02-24 16:41:13     START:Entrance|Leaving
2017-02-24 16:41:14     START:Entrance|Leaving
2017-02-24 16:41:15     START:Entrance|Leaving
2017-02-24 16:41:16      STOP:Entrance|Leaving
Name: label, Length: 383714, dtype: object

In [ ]:
# we are replacing the stop:activity in different activities by a novel class named Transition activity,
all_data['label'] = all_data['label'].apply(lambda x: 'Transition' if x.startswith('STOP') else x)

In [ ]:
all_data['label']

Time
2017-01-30 07:58:30    START:Entrance|Entering
2017-01-30 07:58:32    START:Entrance|Entering
2017-01-30 07:58:33    START:Entrance|Entering
2017-01-30 07:58:36    START:Entrance|Entering
2017-01-30 07:58:38    START:Entrance|Entering
                                ...
2017-02-24 16:41:11     START:Entrance|Leaving
2017-02-24 16:41:13     START:Entrance|Leaving
2017-02-24 16:41:14     START:Entrance|Leaving
2017-02-24 16:41:15     START:Entrance|Leaving
2017-02-24 16:41:16                 Transition
Name: label, Length: 383714, dtype: object

In [ ]:
# we are replacing the Start:activity by activity,
all_data['label'] = all_data['label'].str.replace('START:', '', flags=re.IGNORECASE)

In [ ]:
all_data['label']

Time
2017-01-30 07:58:30    Entrance|Entering
2017-01-30 07:58:32    Entrance|Entering
2017-01-30 07:58:33    Entrance|Entering
2017-01-30 07:58:36    Entrance|Entering
2017-01-30 07:58:38    Entrance|Entering
                             ...
2017-02-24 16:41:11     Entrance|Leaving
2017-02-24 16:41:13     Entrance|Leaving
2017-02-24 16:41:14     Entrance|Leaving
2017-02-24 16:41:15     Entrance|Leaving
2017-02-24 16:41:16           Transition
Name: label, Length: 383714, dtype: object

## Normalizing numerical values using Min-Max

In [ ]:
# Apply min-max scaling
scaler = MinMaxScaler()
for col in numerical_cols:
    all_data[col] = scaler.fit_transform(all_data[[col]])

## Normalizing categorical values using LabelBinarizer

In [ ]:
# Apply LabelBinarizer to binary columns only
lb = LabelBinarizer()
for col in binary_cols:
    all_data[col] = lb.fit_transform(all_data[[col]])

## Normalizing categorical values using One-hot encoding

In [ ]:
# Apply one-hot encoding to binary columns only
encoder = OneHotEncoder()

for col in multi_cols:
    print(col, ' ',all_data[col].unique())

global_wind_direction_ext   ['ENE' 'SSE' 'S' 'E' 'SSW' 'SW' 'WSW' 'W' 'NNW' 'WNW' 'N' 'NE' 'ESE' 'SE'
 'NW' 'NNE']
global_pressure_trend_ext   ['down' 'up' 'equal']
global_condition_ext   ['peu nuageux' 'Couvert' 'lÃ©gÃ¨res pluies' 'brume' 'brouillard'
 'partiellement ensoleillÃ©' 'nuageux' 'ensoleillÃ©']
global_commonID_ext   ['partly-cloudy-day' 'cloudy' 'few-showers' 'fog' 'mostly-cloudy-day'
 'sunny']
label   ['Entrance|Entering' 'Transition' 'Staircase|Going_up'
 'Bathroom|Showering' 'Bathroom|Using_the_sink' 'Staircase|Going_down'
 'Living_room|Watching_TV' 'Toilet|Using_the_toilet' 'Office|Computing'
 'Kitchen|Preparing' 'Kitchen|Cooking' 'Living_room|Eating'
 'Kitchen|Washing_the_dishes' 'Living_room|Cleaning'
 'Living_room|Computing' 'Bedroom|Dressing' 'Bedroom|Reading'
 'Bedroom|Napping' 'Bathroom|Using_the_toilet' 'Office|Watching_TV'
 'Entrance|Leaving' 'Kitchen|Cleaning' 'Bathroom|Cleaning'
 'Bedroom|Cleaning' 'Office|Cleaning']

In [ ]:
all_data

,bedroom_switch_middle_left,entrance_heater_effective_setpoint,bedroom_switch_middle_right,kitchen_noise,livingroom_couch_plug_consumption,global_snow_ext,bedroom_heater1_effective_setpoint,global_lighting_power,livingroom_heater2_base_setpoint,kitchen_dishwasher_current,...,global_waterheater_voltage,kitchen_cupboard4,bathroom_sink_coldwater_instantaneous,bedroom_noise,kitchen_humidity,kitchen_oven_power,global_commonID_ext,kitchen_presence,livingroom_luminosity,label
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-30 07:58:30,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0.000000,1,0.0,0.00000,0.000,0.0,partly-cloudy-day,1,0.000000,Entrance|Entering
2017-01-30 07:58:32,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0.000000,1,0.0,0.00000,0.000,0.0,partly-cloudy-day,1,0.000000,Entrance|Entering
2017-01-30 07:58:33,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0.000000,1,0.0,0.00000,0.000,0.0,partly-cloudy-day,1,0.000000,Entrance|Entering
2017-01-30 07:58:36,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0.000000,1,0.0,0.00000,0.000,0.0,partly-cloudy-day,1,0.000000,Entrance|Entering
2017-01-30 07:58:38,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0.000000,1,0.0,0.00000,0.000,0.0,partly-cloudy-day,1,0.000000,Entrance|Entering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-24 16:41:11,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0.989019,0,0.0,0.07171,0.875,0.0,cloudy,0,0.011103,Entrance|Leaving
2017-02-24 16:41:13,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0.989019,0,0.0,0.07171,0.875,0.0,cloudy,0,0.011103,Entrance|Leaving
2017-02-24 16:41:14,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0.989019,0,0.0,0.07171,0.875,0.0,cloudy,0,0.011103,Entrance|Leaving
2017-02-24 16:41:15,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0.989019,0,0.0,0.07171,0.875,0.0,cloudy,0,0.011103,Entrance|Leaving
2017-02-24 16:41:16,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0.989019,0,0.0,0.07171,0.875,0.0,cloudy,0,0.011103,Transition

In [ ]:
for col in multi_cols:
  # one-hot encode the 'label' column
  one_hot_df = pd.get_dummies(all_data[col])
  # concatenate the original dataframe with the one-hot encoded dataframe
  all_data = pd.concat([all_data, one_hot_df], axis=1)
  # drop the original 'label' column
  all_data.drop(col, axis=1, inplace=True)

In [ ]:
all_data

,bedroom_switch_middle_left,entrance_heater_effective_setpoint,bedroom_switch_middle_right,kitchen_noise,livingroom_couch_plug_consumption,global_snow_ext,bedroom_heater1_effective_setpoint,global_lighting_power,livingroom_heater2_base_setpoint,kitchen_dishwasher_current,...,Living_room|Computing,Living_room|Eating,Living_room|Watching_TV,Office|Cleaning,Office|Computing,Office|Watching_TV,Staircase|Going_down,Staircase|Going_up,Toilet|Using_the_toilet,Transition
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-30 07:58:30,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-01-30 07:58:32,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-01-30 07:58:33,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-01-30 07:58:36,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-01-30 07:58:38,1,0.0,1,0.000000,0.0,0.0,0.0,0.000000,0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-24 16:41:11,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-24 16:41:13,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-24 16:41:14,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-24 16:41:15,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-24 16:41:16,0,1.0,0,0.004371,0.0,0.0,1.0,0.124088,1,0.0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# write the DataFrame to a CSV file (Normalizing the label with Hot encoding)
all_data.to_csv('sensor_data_processed_normalizing_the_label_with_hot_encoding.csv', index=False)